from typing import TypedDict, List, Dict, Optional

class GraphState(TypedDict):
    """
    GraphState defines the structure of the state that is passed through the nodes in the LangGraph. 
    It includes fields for session_id, user query, answer generated by the nodes, classified task type, optional report in markdown format, list of retrieved documents, and a dictionary for grouped documents based on their source or other criteria. This structured state allows for consistent data handling and flow of information across the different nodes in the graph as they process the user query and interact with the retrieved documents to generate insights, summaries, answers, or comparisons.
    """
    session_id: str
    query: str
    answer: Optional[str]
    task: str
    report_md: Optional[str]
    documents: List[Dict]
    grouped_docs: Dict[str, List[Dict]]
    
